apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: ${NAMESPACE}
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    exporters:
      zipkin:
        endpoint: http://zipkin-svc:9411/api/v2/spans
      prometheus:
        endpoint: "0.0.0.0:1234"
      otlphttp:
        endpoint: http://loki-svc:3100/otlp
      otlp:
        endpoint: tempo-svc:9095
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [zipkin, otlp]
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          processors: []
          exporters: [otlphttp]
