apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: ${NAMESPACE}
data:
  dashboard-config.yml: |
    apiVersion: 1
    providers:
      - name: "Dashboard provider"
        orgId: 1
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: false
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: true
  grafana-datasource.yml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      url: http://prometheus-svc:9090 
      access: proxy
      editable: false
      jsonData:
        httpMethod: GET
    - name: Loki
      isDefault: true
      type: loki
      access: proxy 
      url: http://loki-svc:3100
      editable: false
    - name: Zipkin
      type: zipkin
      access: proxy 
      url: http://zipkin-svc:9411
      editable: false
    - name: Tempo
      type: tempo
      access: proxy
      orgId: 1
      url: http://tempo-svc:3200
      basicAuth: false
      isDefault: false
      version: 1
      editable: false
      apiVersion: 1
      uid: tempo
      jsonData:
        httpMethod: GET
        serviceMap:
          datasourceUid: prometheus
  grafana.ini: |
    [dashboards]
    min_refresh_interval = 1s
