apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ${NAMESPACE}
data:
  datasources.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s
    scrape_configs:
    - job_name: CollectorMetrics
      static_configs:
        - targets: 
          - web-svc:8080
    - job_name: 'tempo'
      static_configs:
        - targets: [ 'tempo-svc:3200' ]
