global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
- job_name: CollectorMetrics
  static_configs:
    - targets: 
      - client:8080
- job_name: 'tempo'
  static_configs:
    - targets: [ 'tempo:3200' ]