{
 "title": "Asteroids Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Web Client",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"client\"}"
    }
   ]
  },
  {
   "title": "Cluster Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{service_name=~\"node.*\"}\n| label_format color_service=\"{{if contains \\\"1\\\" .service_name}}\\u001b[91m{{.service_name}}\\u001b[0m{{else if contains \\\"2\\\" .service_name}}\\u001b[32m{{.service_name}}\\u001b[0m{{else if contains \\\"3\\\" .service_name}}\\u001b[94m{{.service_name}}\\u001b[0m{{else}}{{.service_name}}{{end}}\"\n| line_format \"{{.color_service}} - {{__line__}}\"\n"
    }
   ]
  },
  {
   "title": "Unhandled Akka Messages",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} \n| json \n| body =~ \"(Dead|Unhandled) letter: Sender .*Message: .*\"\n| line_format `{{ .body | replace \"{Sender}\" .attributes_Sender | replace \"{Recipient}\" .attributes_Recipient | replace \"{Message}\" .attributes_Message }}`"
    }
   ]
  }
 ]
}