apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  url: http://prometheus:9090 
  isDefault: true
  access: proxy
  editable: false
  jsonData:
    httpMethod: GET
- name: Loki
  type: loki
  access: proxy 
  url: http://loki:3100
  editable: false
- name: Zipkin
  type: zipkin
  access: proxy 
  url: http://zipkin:9411
  editable: false
- name: Tempo
  type: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  apiVersion: 1
  uid: tempo
  jsonData:
    httpMethod: GET
    serviceMap:
      datasourceUid: prometheus