name: Build and deploy on kubernetes
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build web image
        run: |
          nix-shell -p dotnetCorePackages.dotnet_9.sdk --run '
            cd Web
            dotnet publish \
              -c Release \
              --os linux --arch x64 \
              /t:PublishContainer \
              -p:ContainerRepository=yourImageName \
              -p:ContainerImageTags=${{ github.run_number }}

            docker push yourImageName:${{ github.run_number }}
          '

      - name: Deploy to Kubernetes
        run: |
          nix-shell -p kubectl --run '
            export IMAGE_TAG=${{ github.run_number }}
            export NAMESPACE=changeMe 
            
            for file in kube/*; do 
              cat "$file" | envsubst | kubectl apply -f -; 
            done

            kubectl -n $NAMESPACE delete configmap grafana-dashboard-config || true
            kubectl -n $NAMESPACE create configmap grafana-dashboard-config --from-file=configs/grafana/asteroids-kube.json
          '
